spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: online-store-service
          service-host-type: ip
        url: http://172.17.0.1:8083
  datasource:
    url: jdbc:postgresql://172.17.0.1:5433/online-store
    username: admin
    password: admin
  flyway:
    schemas:
      - public
      - online-store
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/online-store
      client:
        registration:
          keycloak:
            client-id: online-store-service-metrics-client
            client-secret: MN4Ul5kHntDOMZ1XwoDZKQbILpmvC1hA
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/online-store
keycloak:
  uri: http://172.17.0.1:8082
springdoc:
  swagger-ui:
    oauth:
      client-id: online-store-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always