server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/online-store
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/online-store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-server
            client-secret: aTHpE7qfJbju7fxgi7IxokG3eAOfaew9
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-server
            client-secret: aTHpE7qfJbju7fxgi7IxokG3eAOfaew9