name: online-store
services:
  # Infrastructure
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/docker/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command: start-dev --import-realm
  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3000:3000'
    volumes:
      - './data/grafana:/var/lib/grafana'
    user: '1000'
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - './config/docker/victoria-metrics/promscrape.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
  db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: online-store
  # Services
  admin-server:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-server/target/admin-server-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/online-store/admin-server:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8083:8083'
  customer-app:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: customer-app/target/customer-app-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/online-store/customer-app:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8081:8081'
  online-store-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: online-store-service/target/online-store-service-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/online-store/online-store-service:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'
  manager-app:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-app/target/manager-app-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/online-store/manager-app:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8084:8084'