scrape_configs:
  - job_name: admin_server
    static_configs:
      - targets: [ "172.17.0.1:8083" ]
        labels:
          application: admin-server
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: QSTXQ3Sl96xDIEKcbNjk2Jrn73OeH39n
      token_url: http://172.17.0.1:8082/realms/online-store/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: customer_app
    static_configs:
      - targets: [ "http://172.17.0.1:8081" ]
        labels:
          application: customer-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: QSTXQ3Sl96xDIEKcbNjk2Jrn73OeH39n
      token_url: http://172.17.0.1:8082/realms/online-store/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: online_store_service
    static_configs:
      - targets: [ "http://172.17.0.1:8080" ]
        labels:
          application: online-store-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: QSTXQ3Sl96xDIEKcbNjk2Jrn73OeH39n
      token_url: http://172.17.0.1:8082/realms/online-store/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials