apiVersion: v1
kind: ConfigMap
metadata:
  name: online-store-service-vmagent-cm
data:
  promscrape.yaml: |
    scrape_configs:
      - job_name: online_store_service
        static_configs:
          - targets: ["http://localhost:8080"]
            labels:
              application: online-store-service
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: G6FYzJibXfpyFDi2hZuWNfBUlB5lRAWm
          token_url: http://keycloak.online.store.192.168.49.2.nip.io/realms/online-store/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store-service-deployment
  labels:
    app: online-store-service
spec:
  selector:
    matchLabels:
      app: online-store-service
  template:
    metadata:
      labels:
        app: online-store-service
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: online-store-service-vmagent-cm
        - name: service-config
          configMap:
            name: online-store-service-config
      containers:
        - name: online-store-service
          image: 192.168.49.1:5000/online-store/online-store-service:0.0.1
          args:
            - --spring.config.import=/etc/opt/online-store-service/application-k8s.yaml
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          volumeMounts:
            - mountPath: /etc/opt/online-store-service
              name: service-config
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yaml
            - -remoteWrite.url=http://vm-svc.online-store.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig
---
apiVersion: v1
kind: Service
metadata:
  name: online-store-service-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: online-store-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-store-service-ingress
spec:
  rules:
    - host: api.online.store.192.168.49.2.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: online-store-service-svc
                port:
                  name: http
