online-store:
  services:
    online-store-service:
      uri: http://localhost:8080
      registration-id: keycloak

server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8083
        instance:
          name: customer-app
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/online-store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: xbpAeDCjrlRelfLjtHicQZ2qtpXfzd0z
            scope:
              - openid
              - microprofile-jwt
              - create_product_review
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: ExxpARTtGiQTusgmDw6oizP7GFvq18hH
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/online-store
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'