image: 192.168.49.1:5000/online-store/online-store-service:0.0.1
vmagent:
  image: victoriametrics/vmagent:v1.93.12
  remoteWrite:
    url: http://vm-svc.online-store.svc.cluster.local:8428/api/v1/write
ingress:
  host: api.online.store.192.168.49.2.nip.io
