server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.online.store.192.168.49.2.nip.io/realms/online-store
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.online.store.192.168.49.2.nip.io/realms/online-store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-server
            client-secret: atSjwGR5vyhfS1hgbFdt6uu1zq4pCFfo
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-server
            client-secret: atSjwGR5vyhfS1hgbFdt6uu1zq4pCFfo
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
