scrape_configs:
  - job_name: online_store_admin_server
    static_configs:
      - targets: ["http://localhost:8080"]
        labels:
          application: online-store-admin-server
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: G6FYzJibXfpyFDi2hZuWNfBUlB5lRAWm
      token_url: http://keycloak.online.store.192.168.49.2.nip.io/realms/online-store/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
